[package]
name = "sunset_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.92"
quote = "1.0.37"
chrono = "0.4.38"
syn = { version = "2.0.90", features = ["proc-macro", "parsing"] }
rocket = { version = "0.5.1", features = ["json"] }
