name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update stable nightly
          rustup component add --toolchain stable clippy
          rustup component add --toolchain nightly rustfmt
          rustup default stable
      - name: Run fmt
        run: cargo +nightly fmt -- --check
      - name: Run clippy
        run: cargo clippy -- -D warnings
      - name: Run tests
        run: cargo test --verbose
